/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadWindowsZipRouteImport } from './routes/download/windows-zip'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadWindowsZipRoute = DownloadWindowsZipRouteImport.update({
  id: '/download/windows-zip',
  path: '/download/windows-zip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download/windows-zip': typeof DownloadWindowsZipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download/windows-zip': typeof DownloadWindowsZipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download/windows-zip': typeof DownloadWindowsZipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/download/windows-zip'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/download/windows-zip'
  id: '__root__' | '/' | '/download/windows-zip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadWindowsZipRoute: typeof DownloadWindowsZipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/windows-zip': {
      id: '/download/windows-zip'
      path: '/download/windows-zip'
      fullPath: '/download/windows-zip'
      preLoaderRoute: typeof DownloadWindowsZipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadWindowsZipRoute: DownloadWindowsZipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
